### ISSUE TITLE
samconfig.toml doesn't exist at docs link

### ISSUE THREAD

**Issue by jonathanhle** [gemini-oss/starfleet#19]
Docs link is outdated or dead - under https://gemini-oss.github.io/starfleet/installation/RunSAM/#sam-configuration:

samconfig.toml doesn't exist at docs link

> When setting up SAM, it will create a configuration. A sample configuration has been provided here that you should use: [samconfig.toml](https://github.com/gemini-oss/starfleet/blob/main/samconfig.toml).

**Comment by mikegrima** [comment]
We should just include the `samconfig.toml` file and update the instructions to have users make the SAM bucket or use an existing one.

I did the hard thing by asking users to first create everything and then update the SAM config later.

**Comment by mikegrima** [comment]
I'm going to fix this on my next docs push which will be soon.

**Comment by mikegrima** [comment]
Fixed in #29
